### ISSUE TITLE
Getting started question

### ISSUE THREAD

**Issue by bcraun** [cboecking/com.chuboe.moeboe#1]

**Comment by cboecking** [comment]
Hi Bill,

The repository has all the artifacts needed to run the application
(including the /cnf). You would clone it to your local machine, open the
application folder, and execute the bndrun. You can call me if you wish to
discuss. 512.850.6068 - Chuck

Regards,

Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by bcraun** [comment]
Hi Chuck,

Thanks so much for responding and the offer of help. As soon as I posted
the question, I saw in the repo that the /cnf existed so I cloned and, sure
enough, compiled and ran right away. I tried to immediately close the
issue, but I guess I wasn’t fast enough.

I want to also thank you for the excellent video tutorial you made
describing the enRoute process. It really helped me and served to fill in
some missing pieces from the official tutorial. I wound up sending an email
to Peter Kriens before I found your webcast looking for help. I am totally
new to OSGi and am building an IoT Gateway for a client and chose to base
it on OSGi. I have a month to deliver so am in a bit of a pinch in terms of
learning curve. I need as many examples as I can find from which to draw
patterns, etc. I was looking at your persistence sample as a reference
since I will likely need a document DB like Mongo. Anyway, I started poring
through the code to make sense of how I need to structure things.
Hopefully, it’s pretty self-documenting. If I run into any issues or have
the occasional question, would you consider a direct email from me
appropriate?

Thanks again,
Bill

**Comment by cboecking** [comment]
Bill,

Absolutely. You can reach me at chuck@chuboe.com (www.chuckboecking.com).
Good luck.

Regards,

Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by bcraun** [comment]
Hi Chuck,

Just a quick question to get your opinion on adding MongoDB support to an
enRoute app. I studied the sample you put together with the extensive use
of DTOs and I’m not sure I’m at the stage to get my head around the breadth
of what’s going on. At this point, I am looking to add the driver for
Peter, begin logging app telemetry using a strongly-typed DTO. Is there an
example of something along those lines or can you point me to the
appropriate projects in your database sample? I get the concepts it’s just
the OSGi way of separation of concerns and use of dynamic services that
makes it challenging to follow the app workflow.

Thanks so much,
Bill

**Comment by cboecking** [comment]
Hi Bill,

If I understand you correctly, you are not looking for a CRUD solution, you
are simply looking to persist stuff. Here are two tests that Peter created:
- Test #1
  https://github.com/pkriens/aQute.open/blob/master/aQute.open.store.test/src/aQute/open/store/test/StoreTest.java
- created as an API test. Said another way, it is an outsider of the
  provider bundle looking in. This is similar to this step in the basic
  tutorial http://enroute.osgi.org/tutorial_base/600-testing.html.
- Test #2
  https://github.com/pkriens/aQute.open/tree/master/aQute.open.store.mongo.provider/test/aQute/impl/store/mongo
- traditional test inside the provider itself. This is similar to this
  step in the basic tutorial
  http://enroute.osgi.org/tutorial_base/340-junit.html.

Does this help?

Regards,

Chuck Boecking
512.850.6068 (office and cell)
chuck@chuboe.com
ChuckBoecking.com
chuck.boecking (skype)
@ChuckBoecking
http://www.linkedin.com/pub/chuck-boecking/10/970/17b

**Comment by bcraun** [comment]
Hi Chuck,

Yes, that does. Thanks.

Bill

**Comment by bcraun** [comment]
Hi Chuck,

In your CRUD sample, what does “PO” represent; purchase order?

Thanks,
Bill

**Comment by bcraun** [comment]
PO —> Persistence Object ?

**Comment by cboecking** [comment]
Yes -persistent object

**Comment by bcraun** [comment]
Got it, thanks!

Bill
